import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased lg:max-w-7xl lg:mx-auto`}
      >
        <div className="p-2">
          <h1 className="text-xl md:text-2xl">My Awesome Shop</h1>
        </div>
        {children}
        <div className="p-2">
          <h1>Footer</h1>
        </div>
      </body>
    </html>
  );
}
